name:  Build and Publish Docker Image

on:
  workflow_dispatch:

jobs:
  build-and-publish:
    name:  Build & Push kenjitsu-api Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name:  Checkout repository
        uses: actions/checkout@v4

      - name:  Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name:  Build Docker image
        run: |
          docker build \
            --build-arg NPM_TOKEN=${{ secrets.GH_PACKAGES_TOKEN }} \
            -t ghcr.io/${{ github.repository_owner }}/kenjitsu-api:latest .

      - name:  Push Docker image
        run: docker push ghcr.io/${{ github.repository_owner }}/kenjitsu-api:latest
